# Desafio 3
## Ejercicio 1
### A. Construir arrays a partir de una lista simple y una lista anidada usando tipos de datos numericos distintos para cada una.

In [8]:
import numpy as np
import random

arr_simple = np.array([1.1,1.2,1.3,1.4], dtype= np.float64)
print(arr_simple)

arr_anidado = np.array([[1,2,3,4], [5,6,7,8]], dtype= np.int8)
print(arr_anidado)


[1.1 1.2 1.3 1.4]
[[1 2 3 4]
 [5 6 7 8]]


### B. Construir un array lineal de 36 elementos. Cambiar el shape para que tenga: 3 filas y 12 columnas; 4 columnas

In [12]:
arr_B = np.array([random.randint(1,10) for n in range(36)], dtype= np.int8)
print(arr_B)

[ 5  2  9  9  8  7  5  3 10  6  1  5  7  9  9 10  7  8  8  8  2  7  5  2
  7  5  4  9  2  4  7  4  8  4  4  6]


In [20]:
arr_B_3x12 = arr_B.reshape(3,12)
print(arr_B_3x12)

[[ 5  2  9  9  8  7  5  3 10  6  1  5]
 [ 7  9  9 10  7  8  8  8  2  7  5  2]
 [ 7  5  4  9  2  4  7  4  8  4  4  6]]


In [23]:
arr_B_9x4 = arr_B.reshape(9,4)
print(arr_B_9x4)

[[ 5  2  9  9]
 [ 8  7  5  3]
 [10  6  1  5]
 [ 7  9  9 10]
 [ 7  8  8  8]
 [ 2  7  5  2]
 [ 7  5  4  9]
 [ 2  4  7  4]
 [ 8  4  4  6]]


## Ejercicio 2
### Dado un vector de pesos(kg) y otro vector alturas(metros), calcular el indice de masa corporal general (un vector imc)

In [25]:
pesos = np.array([50,65.5,89.2,100], dtype=np.float64)
alturas = np.array([1.6,1.7,1.8,1.75], dtype=np.float64)

imc = pesos/alturas
print(imc)

[31.25       38.52941176 49.55555556 57.14285714]


## Ejercicio 3
### 1. Crear un vector con diez numeros, todos ceros

In [26]:
diez_ceros = np.array([0 for n in range(10)], dtype=np.int8)
print(diez_ceros)

[0 0 0 0 0 0 0 0 0 0]


### 2. Crear un vector con diez numeros al azar

In [27]:
diez_azar = np.array([random.randint(1,10) for n in range(10)], dtype=np.int8)
print(diez_azar)

[ 5  2  9 10  8 10  4  3  8  5]


### 3. Crear una matriz de 2x3 y multiplicarla por su transpuesta

In [34]:
matriz_2x3 = np.array([[2,4,6],[8,10,12]], dtype=np.int8)
matriz_2x3_transpuesta = matriz_2x3.T

matrices_multiplicadas = matriz_2x3 * matriz_2x3_transpuesta
print(matrices_multiplicadas)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 